Inverted section in portlet.xml caused a runtime exception
GRAVE: Cannot read portlet.xml
jndi:/localhost/logomattic/WEB-INF/portlet.xml
org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content
was found starting with element 'init-param'. One of
'{"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":portlet-prefe
rences,
"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":security-role-r
ef,
"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":supported-proce
ssing-event,
"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":supported-publi
shing-event,
"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":supported-publi
c-render-parameter,
"http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd":container-runti
me-option}' is expected.